# Generated by Django 6.0.6 on 2026-06-15 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dr. Kalpesh Manager (Patidar)', max_length=200)),
                ('qualification', models.CharField(default='M.B.B.S, MD', max_length=400)),
                ('specialization', models.CharField(default='Children & New Born Specialist', max_length=300)),
                ('experience', models.IntegerField(default=12, help_text='Years of experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=350.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor/')),
                ('about', models.TextField(blank=True, default='Dr. Kalpesh Patidar is a dedicated Children and Newborn Disease Specialist with over 12 years of experience in pediatric medicine. His compassionate approach and expertise have made Vatsalya Shree Hospital a trusted name for child healthcare in Dhamnod, Madhya Pradesh.')),
                ('reg_no', models.CharField(blank=True, default='', max_length=100)),
                ('languages', models.CharField(blank=True, default='Hindi, English', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profile',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vatsalya Shree Hospital', max_length=200)),
                ('tagline', models.CharField(default='Towards Better Child Health', max_length=300)),
                ('address', models.TextField(default='A.B. Road, Guljhara, Dhamnod, Madhya Pradesh')),
                ('mobile', models.CharField(default='+91-XXXXXXXXXX', max_length=20)),
                ('whatsapp', models.CharField(default='+91-XXXXXXXXXX', max_length=20)),
                ('email', models.EmailField(default='info@vatsalyashreehospital.com', max_length=254)),
                ('reg_no', models.CharField(default='NH/7245/MAY-2026', max_length=100)),
                ('opd_morning', models.CharField(default='10:00 AM – 2:00 PM', max_length=100)),
                ('opd_evening', models.CharField(default='5:00 PM – 8:00 PM', max_length=100)),
                ('working_days', models.CharField(default='Tuesday to Sunday', max_length=200)),
                ('holiday', models.CharField(default='Monday', max_length=100)),
                ('map_embed_url', models.URLField(blank=True, default='', help_text='Google Maps embed URL (iframe src)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Info',
                'verbose_name_plural': 'Hospital Info',
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(blank=True, default='', max_length=500)),
                ('prescription', models.TextField(blank=True, default='')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospital.patient')),
            ],
            options={
                'verbose_name': 'Visit History',
                'verbose_name_plural': 'Visit Histories',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
